### ISSUE TITLE
Composer file still says justintadlock/hybrid-core instead of justintadlock/hybrid-tools

### ISSUE THREAD

**Issue by skyshab** [themehybrid/hybrid-tools#1]
The composer file still says justintadlock/hybrid-core instead of justintadlock/hybrid-tools, making it not able to be installed.

**Comment by saas786** [comment]
Fixed in: https://github.com/themehybrid/hybrid-tools/commit/cbdcfbd466bcd4586eb34efd1f154d072b35698a#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L2
